[package]
name = "piece-table"
version = "0.1.0"
edition = "2024"

[dependencies]
fnv = "1.0.7"
fxhash = "0.2.1"
rand = "0.9.2"
ropey = "1.6.1"

[dev-dependencies]
proptest = "1.5.0"
criterion = "0.5"

[[bench]]
name = "create"
harness = false

[[bench]]
name = "insert"
harness = false
